#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.18052
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Funky_Film.Resource", IsApplication=true)]

namespace Funky_Film
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Resource.String.ApplicationName = global::Funky_Film.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::Funky_Film.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_horizontal_margin = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int activity_vertical_margin = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int content_txt_size = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int icon_size = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int poster_size = 2131099651;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int default_actor_image = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int default_crew_image = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int default_movie_image = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int FFIcon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int monoandroidsplash = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090033
			public const int action_search = 2131296307;
			
			// aapt resource value: 0x7f090032
			public const int action_settings = 2131296306;
			
			// aapt resource value: 0x7f090001
			public const int actor_name = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int actor_role = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int actor_thumbnail = 2131296256;
			
			// aapt resource value: 0x7f090006
			public const int add_cnt_list = 2131296262;
			
			// aapt resource value: 0x7f090005
			public const int credit_role = 2131296261;
			
			// aapt resource value: 0x7f090003
			public const int credit_thumbnail = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int credit_title = 2131296260;
			
			// aapt resource value: 0x7f09000c
			public const int crew_job = 2131296268;
			
			// aapt resource value: 0x7f09000b
			public const int crew_name = 2131296267;
			
			// aapt resource value: 0x7f09000a
			public const int crew_thumbnail = 2131296266;
			
			// aapt resource value: 0x7f090031
			public const int detail_cnt_adult = 2131296305;
			
			// aapt resource value: 0x7f09001b
			public const int detail_cnt_overview = 2131296283;
			
			// aapt resource value: 0x7f090012
			public const int detail_cnt_rating = 2131296274;
			
			// aapt resource value: 0x7f090017
			public const int detail_cnt_releasedate = 2131296279;
			
			// aapt resource value: 0x7f090018
			public const int detail_cnt_runtime = 2131296280;
			
			// aapt resource value: 0x7f090015
			public const int detail_cnt_status = 2131296277;
			
			// aapt resource value: 0x7f090030
			public const int detail_overview = 2131296304;
			
			// aapt resource value: 0x7f090010
			public const int detail_poster = 2131296272;
			
			// aapt resource value: 0x7f090013
			public const int detail_rating = 2131296275;
			
			// aapt resource value: 0x7f090016
			public const int detail_releasedate = 2131296278;
			
			// aapt resource value: 0x7f090019
			public const int detail_runtime = 2131296281;
			
			// aapt resource value: 0x7f090014
			public const int detail_status = 2131296276;
			
			// aapt resource value: 0x7f09001a
			public const int detail_tagline = 2131296282;
			
			// aapt resource value: 0x7f090011
			public const int detail_title = 2131296273;
			
			// aapt resource value: 0x7f090008
			public const int empty = 2131296264;
			
			// aapt resource value: 0x7f090007
			public const int emptyView = 2131296263;
			
			// aapt resource value: 0x7f09002f
			public const int list = 2131296303;
			
			// aapt resource value: 0x7f09002d
			public const int list_title = 2131296301;
			
			// aapt resource value: 0x7f09000d
			public const int movie_container = 2131296269;
			
			// aapt resource value: 0x7f09002c
			public const int movie_search = 2131296300;
			
			// aapt resource value: 0x7f09001c
			public const int myButton = 2131296284;
			
			// aapt resource value: 0x7f090028
			public const int person_bio_cnt = 2131296296;
			
			// aapt resource value: 0x7f090021
			public const int person_birthdate = 2131296289;
			
			// aapt resource value: 0x7f090022
			public const int person_birthdate_cnt = 2131296290;
			
			// aapt resource value: 0x7f090023
			public const int person_birthplace_cnt = 2131296291;
			
			// aapt resource value: 0x7f09001d
			public const int person_container = 2131296285;
			
			// aapt resource value: 0x7f090024
			public const int person_deathdate = 2131296292;
			
			// aapt resource value: 0x7f090025
			public const int person_deathdate_cnt = 2131296293;
			
			// aapt resource value: 0x7f090026
			public const int person_homepage = 2131296294;
			
			// aapt resource value: 0x7f090027
			public const int person_homepage_cnt = 2131296295;
			
			// aapt resource value: 0x7f090020
			public const int person_name = 2131296288;
			
			// aapt resource value: 0x7f09001f
			public const int person_poster = 2131296287;
			
			// aapt resource value: 0x7f09002b
			public const int rating = 2131296299;
			
			// aapt resource value: 0x7f090009
			public const int reload = 2131296265;
			
			// aapt resource value: 0x7f09000e
			public const int scrollView1 = 2131296270;
			
			// aapt resource value: 0x7f09001e
			public const int scrollView2 = 2131296286;
			
			// aapt resource value: 0x7f09002e
			public const int separator = 2131296302;
			
			// aapt resource value: 0x7f090029
			public const int thumbnail = 2131296297;
			
			// aapt resource value: 0x7f09002a
			public const int title = 2131296298;
			
			// aapt resource value: 0x7f09000f
			public const int top = 2131296271;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActorRowLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CreditsRowLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CrewFragment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CrewRowLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int DetailActivity = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int DetailFragment = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int PersonActivity = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int PersonDetailFragment = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Rowlayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int SearchActivity = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int SearchFragment = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int TestDetailActivity = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int detail = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int search = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050022
			public const int about = 2131034146;
			
			// aapt resource value: 0x7f050005
			public const int action_settings = 2131034117;
			
			// aapt resource value: 0x7f05001c
			public const int actor_role = 2131034140;
			
			// aapt resource value: 0x7f050011
			public const int adult = 2131034129;
			
			// aapt resource value: 0x7f050004
			public const int app_name = 2131034116;
			
			// aapt resource value: 0x7f05001d
			public const int bio = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int birthday = 2131034142;
			
			// aapt resource value: 0x7f050020
			public const int birthplace = 2131034144;
			
			// aapt resource value: 0x7f050019
			public const int cast = 2131034137;
			
			// aapt resource value: 0x7f050024
			public const int cast_list = 2131034148;
			
			// aapt resource value: 0x7f050018
			public const int crew = 2131034136;
			
			// aapt resource value: 0x7f05001f
			public const int deathday = 2131034143;
			
			// aapt resource value: 0x7f05001a
			public const int director = 2131034138;
			
			// aapt resource value: 0x7f050007
			public const int empty_no_connection = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int empty_search = 2131034118;
			
			// aapt resource value: 0x7f050013
			public const int genres = 2131034131;
			
			// aapt resource value: 0x7f050002
			public const int hello = 2131034114;
			
			// aapt resource value: 0x7f050021
			public const int homepage = 2131034145;
			
			// aapt resource value: 0x7f050012
			public const int keywords = 2131034130;
			
			// aapt resource value: 0x7f050025
			public const int minutes = 2131034149;
			
			// aapt resource value: 0x7f050017
			public const int no_rating = 2131034135;
			
			// aapt resource value: 0x7f05000b
			public const int no_result = 2131034123;
			
			// aapt resource value: 0x7f050023
			public const int other_cast = 2131034147;
			
			// aapt resource value: 0x7f05000d
			public const int overview = 2131034125;
			
			// aapt resource value: 0x7f050026
			public const int rating = 2131034150;
			
			// aapt resource value: 0x7f05000e
			public const int release_date = 2131034126;
			
			// aapt resource value: 0x7f050008
			public const int retry = 2131034120;
			
			// aapt resource value: 0x7f05000f
			public const int runtime = 2131034127;
			
			// aapt resource value: 0x7f050014
			public const int search_fragment_title_popular = 2131034132;
			
			// aapt resource value: 0x7f050016
			public const int search_fragment_title_search = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int search_fragment_title_upcoming = 2131034133;
			
			// aapt resource value: 0x7f05000a
			public const int search_hint = 2131034122;
			
			// aapt resource value: 0x7f050003
			public const int start_app = 2131034115;
			
			// aapt resource value: 0x7f050010
			public const int status = 2131034128;
			
			// aapt resource value: 0x7f05000c
			public const int tagline = 2131034124;
			
			// aapt resource value: 0x7f050009
			public const int title_activity_search = 2131034121;
			
			// aapt resource value: 0x7f05001b
			public const int writer = 2131034139;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Mono_Android_Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int Searchable = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
