#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.18052
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Funky_Film.Resource", IsApplication=true)]

namespace Funky_Film
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int activity_horizontal_margin = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int activity_vertical_margin = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int content_txt_size = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int icon_size = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int poster_size = 2131034115;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int default_actor_image = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int default_crew_image = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int default_movie_image = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int FFIcon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int monoandroidsplash = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090023
			public const int action_search = 2131296291;
			
			// aapt resource value: 0x7f090022
			public const int action_settings = 2131296290;
			
			// aapt resource value: 0x7f090001
			public const int actor_name = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int actor_role = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int actor_thumbnail = 2131296256;
			
			// aapt resource value: 0x7f090003
			public const int add_cnt_list = 2131296259;
			
			// aapt resource value: 0x7f090006
			public const int crew_job = 2131296262;
			
			// aapt resource value: 0x7f090005
			public const int crew_name = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int crew_thumbnail = 2131296260;
			
			// aapt resource value: 0x7f090015
			public const int detail_adult = 2131296277;
			
			// aapt resource value: 0x7f090014
			public const int detail_cnt_adult = 2131296276;
			
			// aapt resource value: 0x7f090019
			public const int detail_cnt_genres = 2131296281;
			
			// aapt resource value: 0x7f090017
			public const int detail_cnt_keywords = 2131296279;
			
			// aapt resource value: 0x7f09000d
			public const int detail_cnt_overview = 2131296269;
			
			// aapt resource value: 0x7f09000f
			public const int detail_cnt_releasedate = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int detail_cnt_runtime = 2131296272;
			
			// aapt resource value: 0x7f090013
			public const int detail_cnt_status = 2131296275;
			
			// aapt resource value: 0x7f090018
			public const int detail_genres = 2131296280;
			
			// aapt resource value: 0x7f090016
			public const int detail_keywords = 2131296278;
			
			// aapt resource value: 0x7f09000c
			public const int detail_overview = 2131296268;
			
			// aapt resource value: 0x7f090009
			public const int detail_poster = 2131296265;
			
			// aapt resource value: 0x7f09000e
			public const int detail_releasedate = 2131296270;
			
			// aapt resource value: 0x7f090011
			public const int detail_runtime = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int detail_status = 2131296274;
			
			// aapt resource value: 0x7f09000b
			public const int detail_tagline = 2131296267;
			
			// aapt resource value: 0x7f09000a
			public const int detail_title = 2131296266;
			
			// aapt resource value: 0x7f090021
			public const int empty = 2131296289;
			
			// aapt resource value: 0x7f090020
			public const int list = 2131296288;
			
			// aapt resource value: 0x7f09001f
			public const int list_title = 2131296287;
			
			// aapt resource value: 0x7f090007
			public const int movie_container = 2131296263;
			
			// aapt resource value: 0x7f09001e
			public const int movie_search = 2131296286;
			
			// aapt resource value: 0x7f09001a
			public const int myButton = 2131296282;
			
			// aapt resource value: 0x7f09001d
			public const int rating = 2131296285;
			
			// aapt resource value: 0x7f090008
			public const int scrollView1 = 2131296264;
			
			// aapt resource value: 0x7f09001b
			public const int thumbnail = 2131296283;
			
			// aapt resource value: 0x7f09001c
			public const int title = 2131296284;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActorRowLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CrewFragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CrewRowLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DetailActivity = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int DetailFragment = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Rowlayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SearchActivity = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SearchFragment = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int TestDetailActivity = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int detail = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int search = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060003
			public const int action_settings = 2131099651;
			
			// aapt resource value: 0x7f060018
			public const int actor_role = 2131099672;
			
			// aapt resource value: 0x7f06000d
			public const int adult = 2131099661;
			
			// aapt resource value: 0x7f060002
			public const int app_name = 2131099650;
			
			// aapt resource value: 0x7f060015
			public const int cast = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int crew = 2131099668;
			
			// aapt resource value: 0x7f060016
			public const int director = 2131099670;
			
			// aapt resource value: 0x7f060004
			public const int empty_search = 2131099652;
			
			// aapt resource value: 0x7f06000f
			public const int genres = 2131099663;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			// aapt resource value: 0x7f06000e
			public const int keywords = 2131099662;
			
			// aapt resource value: 0x7f060013
			public const int no_rating = 2131099667;
			
			// aapt resource value: 0x7f060007
			public const int no_result = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int overview = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int release_date = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int runtime = 2131099659;
			
			// aapt resource value: 0x7f060010
			public const int search_fragment_title_popular = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int search_fragment_title_search = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int search_fragment_title_upcoming = 2131099665;
			
			// aapt resource value: 0x7f060006
			public const int search_hint = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int start_app = 2131099649;
			
			// aapt resource value: 0x7f06000c
			public const int status = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int tagline = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int title_activity_search = 2131099653;
			
			// aapt resource value: 0x7f060017
			public const int writer = 2131099671;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Mono_Android_Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int Searchable = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
